import "./globals.css";
import { Bricolage_Grotesque } from "@next/font/google";
import CommonLayout from "@/layouts/CommonLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CommonLayout>{children}</CommonLayout>
      </body>
    </html>
  );
}
